config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  root 'topics#index'
  resources :topics, except: [:new] do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :content, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_friends, only: [:index, :show, :create, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.order(:created_at).reverse_order
    @topic = Topic.new
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    if @friends.include?(@topic.user)
      @comment = @topic.comments.build
      @comments = @topic.comments
    elsif @topic.user == current_user
      @comment = @topic.comments.build
      @comments = @topic.comments
    else
      redirect_to controller: 'topics', action: 'index'
    end
  end

  # GET /topics/1/edit
  def edit
    if @topic.user_id != current_user.id
      redirect_to controller: 'topics', action: 'index'
    end
  end

  # POST /topics
  # POST /topics.json
  def create
    @topics = Topic.order(:created_at).reverse_order
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    respond_to do |format|
      if @topic.save
        #format.html { redirect_to topic_path(@topic) }
        format.js { render :index }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: '編集が完了しました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    if @topic.user_id != current_user.id
      redirect_to controller: 'topics', action: 'index'
    else
      @topic.destroy
      respond_to do |format|
        format.html { redirect_to topics_url}
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:content)
    end

    def set_friends
      @friends = current_user.followers & current_user.followed_users
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic, remote: true, html: {class: 'form-inline'}) do |f| %>
<%= f.error_messages! %>
<%= f.text_field :content, class: 'form-control', placeholder: "今なにしてる？", size:60 %>
<%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>

app/views/topics/_index.html.erb
      <% topics.each do |topic| %>
          <% if friends.include?(topic.user) %>
            <div class="panel panel-default">
              <div class="panel-body">
                <p><%= link_to profile_img(topic.user), user_path(topic.user) %>
                <strong><%= link_to topic.user.name, user_path(topic.user) %>さん</strong> <%= topic.updated_at.strftime("%Y年%m月%d日 %p %l:%M") %></p>

                <%= link_to topic_path(topic) do %>
                  <h4><%= topic.content %></h4>
                <% end %>
              </div>
              <div class="panel-footer">
                <%= link_to ' コメント', topic_path(topic.id), class: "fa fa-reply fa-lg" %>
                <% if topic.user == current_user %>
                   | <%= link_to ' 編集', edit_topic_path(topic.id), class: "fa fa-pencil-square-o fa-lg" %> | 
                  <%= link_to ' 削除', topic_path(topic.id), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？'} %>
                <% end %>
              </div>
            </div>
          <% elsif topic.user == current_user %>
            <div class="panel panel-default">
              <div class="panel-body">
                <p><%= link_to profile_img(topic.user), user_path(topic.user) %>
                <strong><%= link_to topic.user.name, user_path(topic.user) %>さん</strong> <%= topic.updated_at.strftime("%Y年%m月%d日 %p %l:%M") %></p>

                <%= link_to topic_path(topic) do %>
                  <h4><%= topic.content %></h4>
                <% end %>
              </div>
              <div class="panel-footer">
                <%= link_to ' コメント', topic_path(topic.id), class: "fa fa-reply fa-lg" %> | 
                <% if topic.user == current_user %>
                  <%= link_to ' 編集', edit_topic_path(topic.id), class: "fa fa-pencil-square-o fa-lg" %> | 
                  <%= link_to ' 削除', topic_path(topic.id), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
                <% end %>
              </div>
            </div>
          <% end %>
      <% end %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>編集する</h2>
	    <%= form_for(@topic, remote: true) do |f| %>
		<%= f.error_messages! %>
		<%= f.text_field :content, class: 'form-control' %>
		<br/>
		<%= f.submit '編集', class: 'btn btn-primary' %>
	<% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <%= form_for(@topic, html: {class: 'form-inline'}, remote: true) do |f| %>
    <%= f.error_messages! %>
    <%= f.text_field :content, class: 'form-control', placeholder: "今なにしてる？" %>
    <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
    <br/>
    <div id="topics_area">
      <%= render partial: 'index', locals: { topics: @topics, friends: @friends } %>
    </div>
  </div>
</div>

app/views/topics/index.js.erb
$("#topics_area").html("<%= j(render 'index', { topics: @topics, friends: @friends }) %>")
$(':text').val('')

app/views/topics/show.html.erb
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="topic-text">
      <p class="left"><%= link_to profile_img50(@topic.user), user_path(@topic.user) %>
        <strong><%= link_to @topic.user.name, user_path(@topic.user) %></strong></p>
      
      <h4 class="left"><%= @topic.content %></h4>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @topic.created_at.strftime("%Y年%m月%d日 %p %l:%M") %>
      </p>
      
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <%= link_to '一覧に戻る', topics_path, class: "btn btn-default" %>
  </div>
</div>