config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  root 'topics#index'
  resources :topics, except: [:new] do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed, dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :conversations, foreign_key: "sender_id", dependent: :destroy
  has_many :reverse_conversations, foreign_key: "recipient_id", class_name: "Conversation", dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  
  # def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  #   user = User.where(provider: auth.provider, uid: auth.uid).first

  #   unless user
  #     user = User.new(
  #         name:     auth.extra.raw_info.name,
  #         provider: auth.provider,
  #         uid:      auth.uid,
  #         email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
  #         image_url:   auth.info.image,
  #         password: Devise.friendly_token[0, 20]
  #     )
  #     user.skip_confirmation!
  #     user.save(validate: false)
  #   end
  #   user
  # end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20],
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  
  def self.create_unique_string
    SecureRandom.uuid
  end
  
  mount_uploader :avatar, AvatarUploader
  
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  #フォローしているかどうかを確認する
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  #フォローされているかどうかを確認する
  def followed?(other_user)
    relationships.find_by(follower_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def facebook
    # @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    # if @user.persisted?
      # set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      # sign_in_and_redirect @user, event: :authentication
    # else
      # session["devise.facebook_data"] = request.env["omniauth.auth"]
      # redirect_to new_user_registration_url
    # end
  # end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
    @friends = current_user.followers & current_user.followed_users
  end
  
  def show
    @user = User.find(params[:id])
    @topics = Topic.order(:created_at).reverse_order
    @friends = current_user.followers & current_user.followed_users
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% if current_user == user %>
    <br/><br/>
  <% else %>
    <% unless current_user.following?(user) %>
      <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
        <%= f.hidden_field :followed_id %>
        <%= f.submit "フォローする", class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
        <%= f.submit "フォロー解除", class: "btn" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー一覧</h2>

  <div class="row">
    <% @users.each do |user| %>
      <div class="col-xs-6 col-sm-3 col-md-2">
        <div class="thumbnail">
          <%= link_to profile_img100(user), user_path(user) %>
          <div class="caption">
            <h4><%= link_to user.name, user_path(user) %></h4>
            <%= render 'follow_form', user: user %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h2><%= link_to @user.name, user_path(@user.id) %>さん</h2>
      <p><%= link_to profile_img100(@user), user_path(@user.id) %></p>
    </div> 
  </div> 

  <div class="row">
    <div class="col-sm-6">
      <h3>友達</h3>
      <div class="row">
        <% @friends.each do |user| %>
          <div class="col-xs-6 col-sm-6 col-md-4">
            <div class="thumbnail">
              <%= link_to profile_img100(user), user_path(user) %>
              <div class="caption">
                <h4><%= link_to user.name, user_path(user) %></h4>
                <% if @friends.include?(user) %>
                  <%= link_to conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' do %>
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>メッセージ
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-sm-6">
      <h3><%= @user.name %>の投稿</h3>
      <div id="topics_area">
        <% @topics.each do |topic| %>
          <% if @friends.include?(@user) or current_user == @user %>
            <% if topic.user == @user %>
              <div class="panel panel-default">
                <div class="panel-body">
                  <p><%= link_to profile_img(topic.user), user_path(topic.user) %>
                  <strong><%= link_to topic.user.name, user_path(topic.user) %>さん</strong> <%= topic.updated_at.strftime("%Y年%m月%d日 %p %l:%M") %></p>
                  <%= link_to topic_path(topic) do %>
                    <h4><%= topic.content %></h4>
                  <% end %>
                </div>
                <div class="panel-footer">
                  <%= link_to ' コメント', topic_path(topic.id), class: "fa fa-reply fa-lg" %>
                  <% if topic.user == current_user %>
                     | <%= link_to ' 編集', edit_topic_path(topic.id), class: "fa fa-pencil-square-o fa-lg" %> | 
                    <%= link_to ' 削除', topic_path(topic.id), class: "fa fa-trash-o fa-lg", method: :delete, data: { confirm: '本当に削除していいですか？' } %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
    　　</div>
    </div>
  </div>
</div>