config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]
  root 'topics#index'
  resources :topics, except: [:new] do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebeek</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Facebeek', root_path, { :class => "navbar-brand" } %>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user) do %>
                <%= profile_img(current_user) %>
                <%= current_user.name %>
              <% end %>
            </li>
          <% else %>
            <li><a href="#"><%= image_tag("no_image.png", :size => "20x20", :alt => "アイコン") %>ゲストさん</a></li>
          <% end %>
          <li><%= link_to 'ホーム', root_path %></li>
          <li class="dropdown">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if user_signed_in? %>
                <li><%= link_to 'ユーザー一覧', users_path %></li>
                <li><%= link_to 'マイページ', user_path(current_user) %></li>
                <li><%= link_to 'アカウント設定', edit_user_registration_path %></li>                
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'ログイン', new_user_session_path  %></li>
                <li><%= link_to '新規登録', new_user_registration_path %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>